In [ ]:
# ======================================================
# Topic      : Pandas Day 1
# Author     : Anuj Thakor
# Date       : 06-07-2026
# Objective  : Create and inspect DataFrames.
#              Select, filter, sort, and summarize data.
#              Perform simple analysis on a dataset., 
# ======================================================

In [1]:
import numpy as np
import pandas as pd

In [139]:
data = {
    "Student_ID": [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],

    "Name": [
        "Anuj", "Riya", "Aman", "Priya", "Rahul",
        "Sneha", "Karan", "Neha", "Arjun", "Pooja"
    ],

    "Gender": [
        "Male", "Female", "Male", "Female", "Male",
        "Female", "Male", "Female", "Male", "Female"
    ],

    "Age": [19, 20, 18, 21, 20, 19, 22, 18, 21, 20],

    "Course": [
        "BCA", "BCA", "BSc", "BCA", "BCom",
        "BSc", "BCA", "BCom", "BSc", "BCA"
    ],

    "Python_Marks": [85, 92, 76, 88, 69, 95, 81, 74, 90, 87],

    "NumPy_Marks": [80, 90, 72, 91, 65, 97, 79, 70, 88, 84],

    "Attendance (%)": [92, 96, 85, 98, 80, 99, 89, 83, 95, 91]
}

df = pd.DataFrame(data)

In [140]:
df.head()

,Student_ID,Name,Gender,Age,Course,Python_Marks,NumPy_Marks,Attendance (%)
0,101,Anuj,Male,19,BCA,85,80,92
1,102,Riya,Female,20,BCA,92,90,96
2,103,Aman,Male,18,BSc,76,72,85
3,104,Priya,Female,21,BCA,88,91,98
4,105,Rahul,Male,20,BCom,69,65,80

In [141]:
df.tail()

,Student_ID,Name,Gender,Age,Course,Python_Marks,NumPy_Marks,Attendance (%)
5,106,Sneha,Female,19,BSc,95,97,99
6,107,Karan,Male,22,BCA,81,79,89
7,108,Neha,Female,18,BCom,74,70,83
8,109,Arjun,Male,21,BSc,90,88,95
9,110,Pooja,Female,20,BCA,87,84,91

In [142]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Student_ID      10 non-null     int64
 1   Name            10 non-null     object
 2   Gender          10 non-null     object
 3   Age             10 non-null     int64
 4   Course          10 non-null     object
 5   Python_Marks    10 non-null     int64
 6   NumPy_Marks     10 non-null     int64
 7   Attendance (%)  10 non-null     int64
dtypes: int64(5), object(3)
memory usage: 772.0+ bytes

In [143]:
df.describe()
#this function helps with finding the no. of entries
# and several aggregation functions

       Student_ID        Age  Python_Marks  NumPy_Marks  Attendance (%)
count    10.00000  10.000000     10.000000    10.000000       10.000000
mean    105.50000  19.800000     83.700000    81.600000       90.800000
std       3.02765   1.316561      8.459708    10.297788        6.494442
min     101.00000  18.000000     69.000000    65.000000       80.000000
25%     103.25000  19.000000     77.250000    73.750000       86.000000
50%     105.50000  20.000000     86.000000    82.000000       91.500000
75%     107.75000  20.750000     89.500000    89.500000       95.750000
max     110.00000  22.000000     95.000000    97.000000       99.000000

In [144]:
df.shape

(10, 8)

In [145]:
df.columns

Index(['Student_ID', 'Name', 'Gender', 'Age', 'Course', 'Python_Marks',
       'NumPy_Marks', 'Attendance (%)'],
      dtype='object')

In [146]:
df.dtypes

Student_ID         int64
Name              object
Gender            object
Age                int64
Course            object
Python_Marks       int64
NumPy_Marks        int64
Attendance (%)     int64
dtype: object

In [147]:
#how many students are there?
df['Student_ID'].count()

np.int64(10)

In [148]:
#which columns are numeric?
df.select_dtypes(include='number').columns

Index(['Student_ID', 'Age', 'Python_Marks', 'NumPy_Marks', 'Attendance (%)'], dtype='object')

In [149]:
#what is the average age
df['Age'].mean()

np.float64(19.8)

In [150]:
df[['Name','Gender','Student_ID']]

    Name  Gender  Student_ID
0   Anuj    Male         101
1   Riya  Female         102
2   Aman    Male         103
3  Priya  Female         104
4  Rahul    Male         105
5  Sneha  Female         106
6  Karan    Male         107
7   Neha  Female         108
8  Arjun    Male         109
9  Pooja  Female         110

In [151]:
#Student names only.
#Python and NumPy marks together.
#The first five students.
#The last three students.

In [152]:
df['Name']

0     Anuj
1     Riya
2     Aman
3    Priya
4    Rahul
5    Sneha
6    Karan
7     Neha
8    Arjun
9    Pooja
Name: Name, dtype: object

In [153]:
df[['Python_Marks','NumPy_Marks']]

   Python_Marks  NumPy_Marks
0            85           80
1            92           90
2            76           72
3            88           91
4            69           65
5            95           97
6            81           79
7            74           70
8            90           88
9            87           84

In [154]:
df.head()

,Student_ID,Name,Gender,Age,Course,Python_Marks,NumPy_Marks,Attendance (%)
0,101,Anuj,Male,19,BCA,85,80,92
1,102,Riya,Female,20,BCA,92,90,96
2,103,Aman,Male,18,BSc,76,72,85
3,104,Priya,Female,21,BCA,88,91,98
4,105,Rahul,Male,20,BCom,69,65,80

In [155]:
df.tail(3)

,Student_ID,Name,Gender,Age,Course,Python_Marks,NumPy_Marks,Attendance (%)
7,108,Neha,Female,18,BCom,74,70,83
8,109,Arjun,Male,21,BSc,90,88,95
9,110,Pooja,Female,20,BCA,87,84,91

## Filtering

In [156]:
#Students scoring above 80 in both Python and NumPy.
#Students with attendance below 75%.
#Female students with Python marks above 85.

In [157]:
df[df['Python_Marks'] > 80]

,Student_ID,Name,Gender,Age,Course,Python_Marks,NumPy_Marks,Attendance (%)
0,101,Anuj,Male,19,BCA,85,80,92
1,102,Riya,Female,20,BCA,92,90,96
3,104,Priya,Female,21,BCA,88,91,98
5,106,Sneha,Female,19,BSc,95,97,99
6,107,Karan,Male,22,BCA,81,79,89
8,109,Arjun,Male,21,BSc,90,88,95
9,110,Pooja,Female,20,BCA,87,84,91

In [158]:
df[df['Attendance (%)']>90]

,Student_ID,Name,Gender,Age,Course,Python_Marks,NumPy_Marks,Attendance (%)
0,101,Anuj,Male,19,BCA,85,80,92
1,102,Riya,Female,20,BCA,92,90,96
3,104,Priya,Female,21,BCA,88,91,98
5,106,Sneha,Female,19,BSc,95,97,99
8,109,Arjun,Male,21,BSc,90,88,95
9,110,Pooja,Female,20,BCA,87,84,91

In [159]:
df[df['Age']>19]

,Student_ID,Name,Gender,Age,Course,Python_Marks,NumPy_Marks,Attendance (%)
1,102,Riya,Female,20,BCA,92,90,96
3,104,Priya,Female,21,BCA,88,91,98
4,105,Rahul,Male,20,BCom,69,65,80
6,107,Karan,Male,22,BCA,81,79,89
8,109,Arjun,Male,21,BSc,90,88,95
9,110,Pooja,Female,20,BCA,87,84,91

In [160]:
df[(df['Python_Marks'] > 80) & (df['NumPy_Marks']>80)]

,Student_ID,Name,Gender,Age,Course,Python_Marks,NumPy_Marks,Attendance (%)
1,102,Riya,Female,20,BCA,92,90,96
3,104,Priya,Female,21,BCA,88,91,98
5,106,Sneha,Female,19,BSc,95,97,99
8,109,Arjun,Male,21,BSc,90,88,95
9,110,Pooja,Female,20,BCA,87,84,91

In [161]:
df[df['Attendance (%)'] > 75]

,Student_ID,Name,Gender,Age,Course,Python_Marks,NumPy_Marks,Attendance (%)
0,101,Anuj,Male,19,BCA,85,80,92
1,102,Riya,Female,20,BCA,92,90,96
2,103,Aman,Male,18,BSc,76,72,85
3,104,Priya,Female,21,BCA,88,91,98
4,105,Rahul,Male,20,BCom,69,65,80
5,106,Sneha,Female,19,BSc,95,97,99
6,107,Karan,Male,22,BCA,81,79,89
7,108,Neha,Female,18,BCom,74,70,83
8,109,Arjun,Male,21,BSc,90,88,95
9,110,Pooja,Female,20,BCA,87,84,91

In [162]:
df[(df['Gender'] == 'Female') & (df['Python_Marks']>85)]

,Student_ID,Name,Gender,Age,Course,Python_Marks,NumPy_Marks,Attendance (%)
1,102,Riya,Female,20,BCA,92,90,96
3,104,Priya,Female,21,BCA,88,91,98
5,106,Sneha,Female,19,BSc,95,97,99
9,110,Pooja,Female,20,BCA,87,84,91

In [163]:
df.sort_values("Age",axis = 0)

,Student_ID,Name,Gender,Age,Course,Python_Marks,NumPy_Marks,Attendance (%)
2,103,Aman,Male,18,BSc,76,72,85
7,108,Neha,Female,18,BCom,74,70,83
0,101,Anuj,Male,19,BCA,85,80,92
5,106,Sneha,Female,19,BSc,95,97,99
1,102,Riya,Female,20,BCA,92,90,96
4,105,Rahul,Male,20,BCom,69,65,80
9,110,Pooja,Female,20,BCA,87,84,91
3,104,Priya,Female,21,BCA,88,91,98
8,109,Arjun,Male,21,BSc,90,88,95
6,107,Karan,Male,22,BCA,81,79,89

## Value_count & unique

In [164]:
df[df['Gender'] == 'Male'].value_counts().sum()

np.int64(5)

In [165]:
df[df['Gender'] == 'Female'].value_counts().sum()

np.int64(5)

In [166]:
df['Course'].nunique()

3

In [167]:
df['Age'].unique()

array([19, 20, 18, 21, 22])

## group BY

In [168]:
# Average Python marks by Gender.
# Average Attendance by Course.
# Maximum Python marks by Course.
# Count students in each Course.

# Mini Challenge

# Create a summary table using groupby().

In [169]:
df1 = df.groupby('Gender')['Python_Marks'].mean()

In [170]:
df1

Gender
Female    87.2
Male      80.2
Name: Python_Marks, dtype: float64

In [171]:
df.groupby('Course')["Attendance (%)"].mean()

Course
BCA     93.2
BCom    81.5
BSc     93.0
Name: Attendance (%), dtype: float64

In [172]:
df.groupby('Course')['Student_ID'].value_counts()

Course  Student_ID
BCA     101           1
        102           1
        104           1
        107           1
        110           1
BCom    105           1
        108           1
BSc     103           1
        106           1
        109           1
Name: count, dtype: int64

In [173]:
summary = df.groupby('Course').agg({
    'Python_Marks': ['mean', 'max', 'min'],
    'NumPy_Marks': ['mean', 'max'],
    'Attendance (%)': 'mean',
    'Student_ID': 'count'
})

summary

       Python_Marks         NumPy_Marks     Attendance (%) Student_ID
               mean max min        mean max           mean      count
Course
BCA            86.6  92  81   84.800000  91           93.2          5
BCom           71.5  74  69   67.500000  70           81.5          2
BSc            87.0  95  76   85.666667  97           93.0          3

## Final Mini Project

In [174]:
# class topper (overall average of Python and NumPy).
# Student with the highest attendance.
# Average Python marks.
# Average NumPy marks.
# Students above the class average in Python.
# Students with attendance below 80%.
# Count students by gender.
# Count students by course.
# Create a new column:
# Average
#  Create another column:
# Result ("Pass" if Average ≥ 40, otherwise "Fail")
# Display only the top 5 students based on Average.

In [175]:
df['Average_Marks'] = df['Python_Marks'] + df['NumPy_Marks']
df['Average_Marks']

0    165
1    182
2    148
3    179
4    134
5    192
6    160
7    144
8    178
9    171
Name: Average_Marks, dtype: int64

In [176]:
df.loc[df['Average_Marks'].idxmax()]

Student_ID           106
Name               Sneha
Gender            Female
Age                   19
Course               BSc
Python_Marks          95
NumPy_Marks           97
Attendance (%)        99
Average_Marks        192
Name: 5, dtype: object

In [177]:
df.loc[df['Attendance (%)'].idxmax()]

Student_ID           106
Name               Sneha
Gender            Female
Age                   19
Course               BSc
Python_Marks          95
NumPy_Marks           97
Attendance (%)        99
Average_Marks        192
Name: 5, dtype: object

In [178]:
py_avg = df['Python_Marks'].mean()

In [179]:
np_avg = df['NumPy_Marks'].mean()

In [180]:
df[df['Python_Marks']>py_avg]

,Student_ID,Name,Gender,Age,Course,Python_Marks,NumPy_Marks,Attendance (%),Average_Marks
0,101,Anuj,Male,19,BCA,85,80,92,165
1,102,Riya,Female,20,BCA,92,90,96,182
3,104,Priya,Female,21,BCA,88,91,98,179
5,106,Sneha,Female,19,BSc,95,97,99,192
8,109,Arjun,Male,21,BSc,90,88,95,178
9,110,Pooja,Female,20,BCA,87,84,91,171

In [181]:
df[df['NumPy_Marks']>np_avg]

,Student_ID,Name,Gender,Age,Course,Python_Marks,NumPy_Marks,Attendance (%),Average_Marks
1,102,Riya,Female,20,BCA,92,90,96,182
3,104,Priya,Female,21,BCA,88,91,98,179
5,106,Sneha,Female,19,BSc,95,97,99,192
8,109,Arjun,Male,21,BSc,90,88,95,178
9,110,Pooja,Female,20,BCA,87,84,91,171

In [182]:
df[df['Attendance (%)']<80]

Empty DataFrame
Columns: [Student_ID, Name, Gender, Age, Course, Python_Marks, NumPy_Marks, Attendance (%), Average_Marks]
Index: []

In [183]:
df['Gender'].value_counts()

Gender
Male      5
Female    5
Name: count, dtype: int64

In [184]:
df['Course'].value_counts()

Course
BCA     5
BSc     3
BCom    2
Name: count, dtype: int64

In [187]:
df['Average'] = (df['Python_Marks'] + df['NumPy_Marks'])/2

In [188]:
df['Average'] = np.where(df['Average'] >= 40,"Pass","Fail")

In [189]:
df

,Student_ID,Name,Gender,Age,Course,Python_Marks,NumPy_Marks,Attendance (%),Average_Marks,Average
0,101,Anuj,Male,19,BCA,85,80,92,165,Pass
1,102,Riya,Female,20,BCA,92,90,96,182,Pass
2,103,Aman,Male,18,BSc,76,72,85,148,Pass
3,104,Priya,Female,21,BCA,88,91,98,179,Pass
4,105,Rahul,Male,20,BCom,69,65,80,134,Pass
5,106,Sneha,Female,19,BSc,95,97,99,192,Pass
6,107,Karan,Male,22,BCA,81,79,89,160,Pass
7,108,Neha,Female,18,BCom,74,70,83,144,Pass
8,109,Arjun,Male,21,BSc,90,88,95,178,Pass
9,110,Pooja,Female,20,BCA,87,84,91,171,Pass